name: Merge and Sort Files (keep todo.txt)

on:
  workflow_dispatch:

jobs:
  merge_sort:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Sort todo.txt and merge with mappings.txt
      run: |
        # Ensure any existing temporary files are removed
        rm -f sorted_todo.txt sorted_mappings.txt merged.txt

        # Exclude lines not starting with an English letter, convert to lowercase, remove blank lines, sort, and deduplicate todo.txt
        grep '^[a-zA-Z]' todo.txt | grep -v '^\s*$' | tr '[:upper:]' '[:lower:]' | sort | uniq > sorted_todo.txt

        # Exclude lines not starting with an English letter, convert to lowercase, remove blank lines, sort, and deduplicate mappings.txt
        grep '^[a-zA-Z]' mappings.txt | grep -v '^\s*$' | tr '[:upper:]' '[:lower:]' | sort | uniq > sorted_mappings.txt

        # Merge the sorted files, remove any duplicates
        cat sorted_mappings.txt sorted_todo.txt | sort | uniq > merged.txt

        # Replace mappings.txt with the merged and sorted content
        mv merged.txt mappings.txt

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add mappings.txt
        git commit -m "Sorted todo.txt, filtered lines starting with an English letter, converted to lowercase, and merged with mappings.txt."
        git push
