name: Update README with Mappings Count

on:
  workflow_dispatch:
  push:
    paths:
      - mappings.txt

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Count lines in mappings.txt
        id: count_lines
        run: |
          COUNT=$(wc -l < mappings.txt)
          echo "COUNT=${COUNT}" >> $GITHUB_ENV

      - name: Get current date and time in Dhaka/Asia
        id: get_datetime
        run: |
          CURRENTDATETIME=$(TZ='Asia/Dhaka' date '+%B %d, %Y %I:%M %p')
          echo "CURRENTDATETIME=${CURRENTDATETIME}" >> $GITHUB_ENV

      - name: Update README.md
        run: |
          # Read the current README.md
          if [ -f README.md ]; then
            CONTENT=$(cat README.md)
          else
            CONTENT=""
          fi

          # Define the new lines with bullet symbol and two spaces at the end
          NEW_LINE_COUNT="• **Number of mappings:** ${COUNT}  "
          NEW_LINE_DATE="• **Last updated:** ${CURRENTDATETIME}  "

          # Remove all lines starting with •
          UPDATED_CONTENT=$(echo "$CONTENT" | sed -E '/^•/d')

          # Append new lines at the end
          FINAL_CONTENT=$(echo "$UPDATED_CONTENT" | sed -e '$a\'"$NEW_LINE_COUNT" -e '$a\'"$NEW_LINE_DATE")

          # Write updated content back to README.md
          echo "$FINAL_CONTENT" > README.md

      - name: Commit and push changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: 'github-actions'
          author_email: 'actions@github.com'
          message: 'Update README with mappings count'
